#include "Idioma.h"

#include <atomic>
#include <cstring>
#include <mutex>
#include <string_view>
#include <unordered_map>

// Arquivo gerado a partir do dicionario do autor (scratchpad i18n/dic.py).
namespace masdr {
namespace {

std::atomic<bool> g_ingles{false};

struct Par { const char* pt; const char* en; };

const Par kTextos[] = {
    {"Mostrar todas", "Show all"},
    {"Somente utilitárias", "Utility only"},
    {"Broadcast — no ar agora", "Broadcast — on air now"},
    {"Broadcast — no ar, Américas", "Broadcast — on air, Americas"},
    {"Broadcast — todas", "Broadcast — all"},
    {"Ruído medido: pico %.0f dB, médio %.0f dB. Squelch em %.0f dB. Clique de novo para medir outra vez.", "Measured noise: peak %.0f dB, average %.0f dB. Squelch at %.0f dB. Click again to measure again."},
    {"CONFIGURAÇÃO", "SETTINGS"},
    {"RTL-SDR (em uso)", "RTL-SDR (in use)"},
    {"SDRplay (em uso)", "SDRplay (in use)"},
    {"SALVAR", "SAVE"},
    {"Configuração salva em ", "Settings saved to "},
    {"MEMÓRIAS", "MEMORIES"},
    {"● GRAVANDO %02d:%02d", "● RECORDING %02d:%02d"},
    {"GRAVAR", "RECORD"},
    {"SOBRE", "ABOUT"},
    {"PADRÃO", "DEFAULT"},
    {"Frequência (kHz):", "Frequency (kHz):"},
    {"Grave", "Bass"},
    {"Agudo", "Treble"},
    {"Plano", "Flat"},
    {"Tonalidade", "Tone"},
    {"Volume (MUDO)", "Volume (MUTED)"},
    {"aberto", "open"},
    {"Clique para ajustar o squelch na beirada do silêncio", "Click to set the squelch right at the edge of silence"},
    {"Redutor de Ruído", "Noise Reduction"},
    {"Ganho de RF", "RF Gain"},
    {"Brilho", "Brightness"},
    {"NR ESPECTRAL", "SPECTRAL NR"},
    {"Força do NR ESPECTRAL: %d  (%d dB)", "SPECTRAL NR strength: %d  (%d dB)"},
    {"Hora UTC (a das grades de horários das estações)", "UTC time (the one used in station schedules)"},
    {"Ir para a banda (modo e largura padrão, amostragem direta automática)", "Go to band (default mode and bandwidth, automatic direct sampling)"},
    {"Rádio desligado - clique em OFF para ligar", "Radio off - click OFF to turn it on"},
    {"Clique em OFF para ligar (ou escolha o aparelho em CONFIGURAÇÃO)", "Click OFF to turn on (or choose the device in SETTINGS)"},
    {"%s  |  %s  |  Q: %s  |  Span: %.0f kHz  |  FFT %d  |  Sinal: %.1f dB (SQL %s)  |  %s %s  |  %.3f Msps  |  CPU %.0f%%", "%s  |  %s  |  Q: %s  |  Span: %.0f kHz  |  FFT %d  |  Signal: %.1f dB (SQL %s)  |  %s %s  |  %.3f Msps  |  CPU %.0f%%"},
    {"fechado", "closed"},
    {"sem aparelho", "no device"},
    {"Som: fila %d ms | ajuste x%.3f | faltas %d", "Audio: queue %d ms | adjust x%.3f | underruns %d"},
    {"Som: placa de som não abriu", "Audio: sound card did not open"},
    {"Não foi possível ligar: ", "Could not start: "},
    {"\n\nConfira o aparelho em CONFIGURAÇÃO. No RTL-SDR o driver WinUSB tem de estar instalado (Zadig), como no SDR#.", "\n\nCheck the device in SETTINGS. For RTL-SDR the WinUSB driver must be installed (Zadig), as in SDR#."},
    {"SEM SINAL", "NO SIGNAL"},
    {"Configuração###cfg", "Settings###cfg"},
    {"Aparelho", "Device"},
    {"RTL-TCP (rede)", "RTL-TCP (network)"},
    {"Tipo", "Type"},
    {"Endereço (IP)", "Address (IP)"},
    {"Porta", "Port"},
    {"(nenhum encontrado)", "(none found)"},
    {"Dispositivo", "Device"},
    {"Procurar", "Search"},
    {"(em uso)", "(in use)"},
    {"Recepção", "Reception"},
    {"Taxa de amostragem", "Sample rate"},
    {"%.3f Msps (janela de %.3f MHz)", "%.3f Msps (%.3f MHz window)"},
    {"Desligada (VHF/UHF)", "Off (VHF/UHF)"},
    {"Ligada (HF)", "On (HF)"},
    {"Automática (abaixo de 24 MHz)", "Automatic (below 24 MHz)"},
    {"Amostragem direta (Q)", "Direct sampling (Q)"},
    {"Tamanho da FFT", "FFT size"},
    {"AGC do dongle", "Dongle AGC"},
    {"Ganho (dB)", "Gain (dB)"},
    {"Correção PPM", "PPM correction"},
    {"Bias-T (alimenta LNA)", "Bias-T (powers the LNA)"},
    {"Ganho FI (dB)", "IF gain (dB)"},
    {"AGC da FI", "IF AGC"},
    {"Som", "Audio"},
    {"Padrão do Windows", "Windows default"},
    {"Placa de som (saída)", "Sound card (output)"},
    {"Referência S9 em HF", "S9 reference on HF"},
    {"Referência S9 em VHF", "S9 reference on VHF"},
    {"Retorno do ponteiro", "Needle return"},
    {"Quanto tempo o ponteiro leva para voltar quando o sinal some\n(ex.: quando o squelch fecha em NFM). Mais alto = volta mais devagar.", "How long the needle takes to fall back when the signal disappears\n(e.g. when the squelch closes in NFM). Higher = slower return."},
    {"Conectado ao rtl_tcp ", "Connected to rtl_tcp "},
    {"Conectando...", "Connecting..."},
    {"Aplicar", "Apply"},
    {"Conectando a ", "Connecting to "},
    {"Fechar", "Close"},
    {"Recepção, Som e S-meter valem na hora, enquanto você mexe. \"Aplicar\" só é preciso para trocar de aparelho ou de endereço.", "Reception, Audio and S-meter take effect immediately. \"Apply\" is only needed to change the device or the address."},
    {"Não foi possível abrir o aparelho: ", "Could not open the device: "},
    {"Criar a partir do VFO atual", "Create from current VFO"},
    {"Editar / excluir…", "Edit / delete…"},
    {"Ocultar a régua", "Hide the ruler"},
    {"Mostrar a régua", "Show the ruler"},
    {"Memórias###mem", "Memories###mem"},
    {"Mostrar os nomes em cima do espectro", "Show the names above the spectrum"},
    {"procurar (nome ou kHz)", "search (name or kHz)"},
    {"%d memórias", "%d memories"},
    {"nome para a frequência atual", "name for the current frequency"},
    {"Salvar atual", "Save current"},
    {"Apagar selecionada", "Delete selected"},
    {"Nome", "Name"},
    {"Modo", "Mode"},
    {"Gravação salva em:\n", "Recording saved to:\n"},
    {"Não foi possível criar o arquivo de gravação:\n", "Could not create the recording file:\n"},
    {"Sobre###sobre", "About###sobre"},
    {"Receptor SDR que roda inteiro no Windows (7, 8, 10 e 11), sem navegador.", "SDR receiver that runs entirely on Windows (7, 8, 10 and 11), no browser needed."},
    {"Portátil: não precisa instalar - a configuração fica no RXSDR.ini ao lado do programa.", "Portable: no installation needed - settings are kept in RXSDR.ini next to the program."},
    {"RTL-SDR, RTL-TCP e SDRplay.  Por PU1XTB.", "RTL-SDR, RTL-TCP and SDRplay.  By PU1XTB."},
    {"Licença: uso livre e NÃO COMERCIAL, mantendo o crédito ao autor (LICENSE.txt).", "License: free NON-COMMERCIAL use, keeping the credit to the author (LICENSE.txt)."},
    {"Decodificadores da pasta decoders: de outros autores, com a licença de cada um (TERCEIROS.txt).", "Programs in the decoders folder: by other authors, each under its own license (TERCEIROS.txt)."},
    {"Tela: Dear ImGui (MIT).  Imagens: stb_image (domínio público).", "UI: Dear ImGui (MIT).  Images: stb_image (public domain)."},
    {"%d na lista com \"%s\"", "%d in the list matching \"%s\""},
    {"\"%s\" não está na lista", "\"%s\" is not in the list"},
    {"- escolha para sintonizar -", "- choose to tune -"},
    {"buscar: frequência (8416,5 ou 8.416.5) ou nome (argentina)", "search: frequency (8416,5 or 8.416.5) or name (argentina)"},
    {"%s%s(horarios em UTC)", "%s%s(times in UTC)"},
    {"\n\nNO AR AGORA pela grade ", "\n\nON AIR NOW per schedule "},
    {"\xE2\x97\x8F NO AR  ", "\xE2\x97\x8F ON AIR  "},
    {"Voo", "Flight"},
    {"Prefixo", "Reg."},
    {"Canal", "Channel"},
    {"Visto", "Seen"},
    {"Abrir o voo no FlightAware\n%s", "Open the flight on FlightAware\n%s"},
    {"Abrir o avião no FlightAware\n%s", "Open the aircraft on FlightAware\n%s"},
    {"Frequência", "Frequency"},
    {"VIS automático", "Automatic VIS"},
    {"Reconhece o modo pelo cabeçalho VIS e começa a imagem sozinho", "Detects the mode from the VIS header and starts the image by itself"},
    {"Corrigir inclinação", "Fix slant"},
    {"Mede o relógio da placa de som de quem transmite pelos pulsos de 1200 Hz\ne endireita a imagem (sem isso ela sai torta)", "Measures the transmitter's sound card clock from the 1200 Hz pulses\nand straightens the image (otherwise it comes out slanted)"},
    {"Salvar PNG", "Save PNG"},
    {"Cada imagem recebida vai para a pasta SSTV ao lado do RXSDR.exe", "Each received image goes to the SSTV folder next to RXSDR.exe"},
    {"Começar agora", "Start now"},
    {"Pegou a transmissão no meio (sem o VIS)? Escolha o modo e clique:\na imagem começa já, alinhada pelos próximos pulsos de sincronismo.", "Caught the transmission halfway (no VIS)? Choose the mode and click:\nthe image starts right away, aligned by the next sync pulses."},
    {"Terminar", "Finish"},
    {"Encerra a imagem atual como está (e salva, se tiver pelo menos 1/4)", "Ends the current image as it is (and saves it, if at least 1/4 is done)"},
    {"Limpar imagem", "Clear image"},
    {"Abrir pasta SSTV", "Open SSTV folder"},
    {"esperando uma imagem...", "waiting for an image..."},
    {"decodificador parado", "decoder stopped"},
    {"%s  %dx%d  -  linha %d de %d%s", "%s  %dx%d  -  line %d of %d%s"},
    {"  (pronta)", "  (done)"},
    {"sem imagem", "no image"},
    {"RECEBENDO", "RECEIVING"},
    {"PRONTA", "DONE"},
    {"ESPERANDO VIS", "WAITING FOR VIS"},
    {"Sintonia: %+.0f Hz   Inclinação: %+.0f ppm", "Tuning: %+.0f Hz   Slant: %+.0f ppm"},
    {"Sincronismos: %d   faltaram: %d", "Syncs: %d   missed: %d"},
    {"Sintonize e espere o cabeçalho VIS", "Tune in and wait for the VIS header"},
    {"Recebidas (%d)", "Received (%d)"},
    {"\n(não salva)", "\n(not saved)"},
    {"\nclique para abrir o PNG", "\nclick to open the PNG"},
    {"USB em 20/15/10 m, LSB em 40/80 m. A imagem começa sozinha no VIS; a linha vermelha mostra onde ela está.", "USB on 20/15/10 m, LSB on 40/80 m. The image starts by itself on the VIS; the red line shows where it is."},
    {"Linhas por minuto (vale para o \"Começar agora\"; com o tom de início a fase mede sozinha)", "Lines per minute (used by \"Start now\"; with the start tone the phasing measures it by itself)"},
    {"Automático", "Automatic"},
    {"O tom de início (300 Hz) começa a imagem e o de fim (450 Hz) termina e salva", "The start tone (300 Hz) begins the image and the stop tone (450 Hz) ends and saves it"},
    {"Inverter (negativo)", "Invert (negative)"},
    {"Endireitar sozinho", "Auto-straighten"},
    {"Ao terminar, mede a inclinação pelas linhas verticais do mapa e endireita (só se a melhora for clara)", "When finished, measures the slant from the map's vertical lines and straightens it (only if the improvement is clear)"},
    {"verde na lista = no ar agora (UTC)", "green in the list = on air now (UTC)"},
    {"Pegou o fax no meio? Começa já com o LPM/IOC escolhidos; depois use \"Alinhar margem\"", "Caught the fax halfway? Starts now with the chosen LPM/IOC; then use \"Align margin\""},
    {"Encerra a imagem atual e salva", "Ends the current image and saves it"},
    {"Limpar", "Clear"},
    {"Endireitar", "Straighten"},
    {"Mede a inclinação pelas linhas verticais do mapa", "Measures the slant from the map's vertical lines"},
    {"Inclinação", "Slant"},
    {"Pixels por linha (o relógio de quem transmite fora do nominal)", "Pixels per line (transmitter clock off nominal)"},
    {"Zerar", "Reset"},
    {"Clique na margem...", "Click the margin..."},
    {"Alinhar margem", "Align margin"},
    {"Clique depois na imagem, onde deveria ser a margem esquerda do mapa", "Then click on the image where the map's left margin should be"},
    {"Abrir pasta WEFAX", "Open WEFAX folder"},
    {"tom de início ouvido - esperando a fase...", "start tone heard - waiting for phasing..."},
    {"fase: medindo a margem e as linhas por minuto...", "phasing: measuring the margin and lines per minute..."},
    {"esperando o tom de início (ou clique Começar agora)", "waiting for the start tone (or click Start now)"},
    {"Decodificadores###dec", "Decoders###dec"},
    {"Decodificador", "Decoder"},
    {"Parar", "Stop"},
    {"] parado\n", "] stopped\n"},
    {"Iniciar", "Start"},
    {"Reiniciar", "Restart"},
    {"Selecionar tudo", "Select all"},
    {"Copiar", "Copy"},
    {"Salvar .txt", "Save .txt"},
    {"Texto salvo em ", "Text saved to "},
    {"Não foi possível salvar em ", "Could not save to "},
    {"Inverter (LSB)", "Invert (LSB)"},
    {"Inverter", "Invert"},
    {"verde = no ar agora (grade UTC)", "green = on air now (UTC schedule)"},
    {"PACTOR-I (100 ou 200 baud, shift 200 Hz) em USB. O tom, a velocidade e a polaridade sao achados sozinhos;", "PACTOR-I (100 or 200 baud, 200 Hz shift) in USB. Tone, speed and polarity are found automatically;"},
    {"cada pacote e conferido pelo CRC - texto so aparece quando o pacote chega inteiro.", "each packet is checked by its CRC - text only appears when the packet arrives intact."},
    {"Tom (Hz, 0 = medir sozinho)", "Tone (Hz, 0 = measure automatically)"},
    {"voz %d Hz", "voice %d Hz"},
    {"Ajuste fino da velocidade da voz decodificada (padrão 16150)", "Fine adjustment of the decoded voice speed (default 16150)"},
    {"Linhas do dsd-fme", "dsd-fme lines"},
    {"Voz", "Voice"},
    {"Origem (SRC)", "Source (SRC)"},
    {"Destino (TGT)", "Target (TGT)"},
    {"Q. voz", "Voice q."},
    {"Q. dados", "Data q."},
    {"● VOZ", "● VOICE"},
    {"Zerar contadores", "Reset counters"},
    {"Receba em NFM 12,5 kHz. A voz decodificada sai no lugar do áudio do rádio.", "Receive in NFM 12.5 kHz. The decoded voice replaces the radio audio."},
    {"Inverter espectro (IQ conjugado)", "Invert spectrum (conjugate IQ)"},
    {"Linhas do tetra-rx", "tetra-rx lines"},
    {"Sintonize a portadora TETRA (pi/4-DQPSK, 25 kHz). A voz sai no lugar do áudio.", "Tune the TETRA carrier (pi/4-DQPSK, 25 kHz). The voice replaces the audio."},
    {"SYNC / CÉLULA", "SYNC / CELL"},
    {"procurando portadora", "searching for carrier"},
    {"travado", "locked"},
    {"procurando", "searching"},
    {"Cripto: %s", "Crypto: %s"},
    {"FRAME / RECEPÇÃO", "FRAME / RECEPTION"},
    {"%s Voz: %d quadros", "%s Voice: %d frames"},
    {"Última chamada: %s", "Last call: %s"},
    {"Banda", "Band"},
    {"%s  (%d canais, %.3f Msps)", "%s  (%d channels, %.3f Msps)"},
    {"O rádio vai para o centro da banda (em USB) e o dumphfdl acompanha todos os canais de uma vez. Não mexa na sintonia enquanto ouve.", "The radio goes to the band centre (in USB) and dumphfdl follows all channels at once. Do not change the tuning while listening."},
    {"Posição", "Position"},
    {"Abrir o mapa dos navios", "Open the ship map"},
    {"162,000 MHz: canais 161,975 e 162,025 ao mesmo tempo (mapa do próprio AIS-catcher).", "162.000 MHz: channels 161.975 and 162.025 at the same time (AIS-catcher's own map)."},
    {"Indicativo", "Callsign"},
    {"Velocidade", "Speed"},
    {"Rumo", "Course"},
    {"Abrir no VesselFinder\n%s", "Open on VesselFinder\n%s"},
    {"Abrir no MarineTraffic\n%s", "Open on MarineTraffic\n%s"},
    {"%.1f nós", "%.1f kn"},
    {"Emissora", "Station"},
    {"buscar: frequência (kHz) ou emissora, país, idioma", "search: frequency (kHz) or station, country, language"},
    {"\xE2\x97\x8F No ar agora:", "\xE2\x97\x8F On air now:"},
    {"nenhuma pela grade", "none per schedule"},
    {"Inverter espectro", "Invert spectrum"},
    {"Só se o sinal nunca travar: troca I e Q (espectro de cabeça para baixo)", "Only if the signal never locks: swaps I and Q (upside-down spectrum)"},
    {"Linhas do dream", "dream lines"},
    {"Entrada", "Input"},
    {"IQ chegando ao dream", "IQ reaching dream"},
    {"Tempo", "Time"},
    {"sincronismo de tempo (achou o sinal OFDM)", "time sync (OFDM signal found)"},
    {"Quadro", "Frame"},
    {"sincronismo de quadro", "frame sync"},
    {"canal de acesso rápido: modo, largura e QAM", "fast access channel: mode, bandwidth and QAM"},
    {"descrição do serviço: nome da emissora, idioma, país", "service description: station name, language, country"},
    {"Áudio", "Audio"},
    {"canal principal (o áudio)", "main service channel (the audio)"},
    {"SINAL", "SIGNAL"},
    {"Modo %c   %.0f kHz   intercalador %s", "Mode %c   %.0f kHz   interleaver %s"},
    {"curto", "short"},
    {"longo", "long"},
    {"Modo: -", "Mode: -"},
    {"Doppler %.2f Hz   atraso %.2f ms", "Doppler %.2f Hz   delay %.2f ms"},
    {"Doppler / atraso: -", "Doppler / delay: -"},
    {"Áudio guardado: %.1f s", "Audio buffered: %.1f s"},
    {"EMISSORA", "STATION"},
    {"Programa: %s", "Program: %s"},
    {"Hora da emissora: %s UTC", "Station time: %s UTC"},
    {"Texto:", "Text:"},
    {"Sintonize a frequência anunciada (o centro do canal). Enquanto o áudio DRM não sai limpo, você", "Tune the announced frequency (the channel centre). Until the DRM audio comes out clean, you"},
    {"ouve o rádio normal; quando a luz Áudio fica verde, entra o som decodificado (AAC / xHE-AAC).", "hear the normal radio; when the Audio light turns green, the decoded sound (AAC / xHE-AAC) takes over."},
    {"Precisa de uns 10 dB de SNR em 16-QAM ou 15 dB em 64-QAM.", "Needs about 10 dB of SNR in 16-QAM or 15 dB in 64-QAM."},
    {"131,550 e 131,825 MHz ao mesmo tempo (AM). O rádio fica com o centro no meio dos dois;", "131.550 and 131.825 MHz at the same time (AM). The radio centres between the two;"},
    {"não mexa na sintonia enquanto ouve. Voo e prefixo abrem no FlightAware.", "do not change the tuning while listening. Flight and registration open on FlightAware."},
    {"136,975 MHz (VDL modo 2, 31,5 kbit/s). O dongle passa para 1,05 Msps enquanto ouve.", "136.975 MHz (VDL mode 2, 31.5 kbit/s). The dongle switches to 1.05 Msps while listening."},
    {"Não mexa na sintonia enquanto ouve. Voo e prefixo abrem no FlightAware.", "Do not change the tuning while listening. Flight and registration open on FlightAware."},
    {"O direwolf ouve o áudio do rádio: 1200 baud em FM (VHF) ou 300 baud em USB (HF).", "direwolf listens to the radio audio: 1200 baud in FM (VHF) or 300 baud in USB (HF)."},
    {"Pac.", "Pkts"},
    {"Mensagem", "Message"},
    {"Abrir no aprs.fi\n%s", "Open on aprs.fi\n%s"},
    {"pronta", "done"},
    {"Sintonize o sinal em USB; mede tons, shift e velocidade.", "Tune the signal in USB; measures tones, shift and speed."},
    {"Escolha um decodificador. DMR, TETRA, HFDL, AIS e APRS usam programas da pasta decoders.", "Choose a decoder. DMR, TETRA, HFDL, AIS and APRS use programs from the decoders folder."},
    {"estreita", "narrow"},
    {"média", "medium"},
    {"larga", "wide"},
    {"HFDL (ACARS em HF)", "HFDL (ACARS on HF)"},
    {"AIS (navios)", "AIS (ships)"},
    {"Analisar sinal", "Analyze signal"},
    {"DRM (rádio digital)", "DRM (digital radio)"},
    {"SSTV (imagens)", "SSTV (images)"},
    {"WEFAX (fax meteorológico)", "WEFAX (weather fax)"},
    {"PACTOR-I (Marinha / FEC)", "PACTOR-I (Navy / FEC)"},
    {"Nenhum", "None"},
    {"[CW] iniciado - o tom e a velocidade sao medidos sozinhos\n", "[CW] started - tone and speed are measured automatically\n"},
    {"[RTTY] iniciado - %.2f baud, shift %.0f Hz%s\n", "[RTTY] started - %.2f baud, shift %.0f Hz%s\n"},
    {", invertido", ", inverted"},
    {"[SITOR-B] iniciado - 100 baud, recepcao em USB\n", "[SITOR-B] started - 100 baud, USB reception\n"},
    {"[DSC] iniciado - 100 baud, shift 170 Hz, recepcao em USB\n", "[DSC] started - 100 baud, shift 170 Hz, USB reception\n"},
    {"[PACTOR-I] iniciado - procurando pacotes (100/200 baud, shift 200 Hz, USB)\n", "[PACTOR-I] started - searching for packets (100/200 baud, shift 200 Hz, USB)\n"},
    {"[ALE] iniciado - 2G ALE (MIL-STD-188-141), 8-FSK 125 baud, USB com BW de 3 kHz\n", "[ALE] started - 2G ALE (MIL-STD-188-141), 8-FSK 125 baud, USB with 3 kHz BW\n"},
    {"[SSTV] esperando o VIS (cabecalho) - Robot, Martin, Scottie, SC2 e PD sao reconhecidos sozinhos\n", "[SSTV] waiting for the VIS (header) - Robot, Martin, Scottie, SC2 and PD are detected automatically\n"},
    {"[WEFAX] esperando o tom de inicio (300 Hz) - a fase acerta a margem e as linhas por minuto sozinha\n", "[WEFAX] waiting for the start tone (300 Hz) - phasing sets the margin and lines per minute automatically\n"},
    {"[ANALISE] juntando 12 s de audio do sinal sintonizado...\n", "[ANALYSIS] collecting 12 s of audio from the tuned signal...\n"},
    {"\n[RTTY] tom central medido: %.0f Hz\n", "\n[RTTY] measured centre tone: %.0f Hz\n"},
    {"\n[ANALISE] ", "\n[ANALYSIS] "},
    {"  (sem VIS)", "  (no VIS)"},
    {"  salva em SSTV", "  saved to SSTV"},
    {"  salva em WEFAX", "  saved to WEFAX"},
    {"  (nao consegui salvar em ", "  (could not save to "},
    {"Parado", "Stopped"},
    {"tom %.0f Hz  |  %.0f palavras/min  |  %d letras", "tone %.0f Hz  |  %.0f words/min  |  %d letters"},
    {"%s  |  tom %.0f Hz  |  %d caracteres  |  %d erros", "%s  |  tone %.0f Hz  |  %d characters  |  %d errors"},
    {"SINCRONIZADO", "SYNCED"},
    {"%s  |  %s  |  tom %.0f Hz  |  %d pacotes (%d somados)  |  %s%s%s", "%s  |  %s  |  tone %.0f Hz  |  %d packets (%d combined)  |  %s%s%s"},
    {"%s  |  %d/%d validos  |  %d salvos pela copia RX", "%s  |  %d/%d valid  |  %d recovered by the RX copy"},
    {"%s  |  %d mensagens  |  %d/%d simbolos validos", "%s  |  %d messages  |  %d/%d valid symbols"},
    {"%s  |  %d palavras  |  %d chamadas  |  desvio %+.0f Hz", "%s  |  %d words  |  %d calls  |  offset %+.0f Hz"},
    {"TRAVADO", "LOCKED"},
    {"dsd-fme rodando  |  %s  |  CC %s  |  %d linhas", "dsd-fme running  |  %s  |  CC %s  |  %d lines"},
    {"sem sincronismo", "no sync"},
    {"procurando a portadora...", "searching for the carrier..."},
    {"%s  |  AFC %+.0f Hz  |  %d bursts  |  voz %d", "%s  |  AFC %+.0f Hz  |  %d bursts  |  voice %d"},
    {"dumphfdl parado", "dumphfdl stopped"},
    {"o radio saiu da banda - clique Reiniciar  |  %d mensagens", "the radio left the band - click Restart  |  %d messages"},
    {"dumphfdl ouvindo  |  %d mensagens", "dumphfdl listening  |  %d messages"},
    {"acarsdec parado", "acarsdec stopped"},
    {"dumpvdl2 parado", "dumpvdl2 stopped"},
    {"o radio saiu do centro combinado - clique Reiniciar  |  %d mensagens", "the radio left the combined centre - click Restart  |  %d messages"},
    {"%s ouvindo  |  %d mensagens", "%s listening  |  %d messages"},
    {"AIS-catcher parado", "AIS-catcher stopped"},
    {"AIS-catcher ouvindo  |  %d mensagens  |  %s", "AIS-catcher listening  |  %d messages  |  %s"},
    {"direwolf parado", "direwolf stopped"},
    {"direwolf ouvindo  |  %d pacotes  |  %s", "direwolf listening  |  %d packets  |  %s"},
    {"dream parado", "dream stopped"},
    {"abrindo o dream...", "starting dream..."},
    {"procurando o sinal DRM  |  sintonize o centro do canal", "searching for the DRM signal  |  tune the channel centre"},
    {"sinal achado, sincronizando (FAC)  |  SNR %.1f dB", "signal found, synchronizing (FAC)  |  SNR %.1f dB"},
    {"DRM %s  |  SNR %.1f dB  |  modo %c  %.0f kHz  %s  |  %s %.1f kbps%s", "DRM %s  |  SNR %.1f dB  |  mode %c  %.0f kHz  %s  |  %s %.1f kbps%s"},
    {"(lendo SDC)", "(reading SDC)"},
    {"  |  áudio com erros", "  |  audio with errors"},
    {"recebendo %s%s  |  linha %d de %d  |  sintonia %+.0f Hz  |  inclinacao %+.0f ppm", "receiving %s%s  |  line %d of %d  |  tuning %+.0f Hz  |  slant %+.0f ppm"},
    {"esperando o VIS  |  sinal %.0f dB  |  %d imagens recebidas", "waiting for the VIS  |  signal %.0f dB  |  %d images received"},
    {"esperando o tom de inicio", "waiting for the start tone"},
    {"tom de inicio - IOC %d", "start tone - IOC %d"},
    {"fase: medindo a margem e as linhas por minuto", "phasing: measuring the margin and lines per minute"},
    {"recebendo", "receiving"},
    {"recebendo  |  %d LPM, IOC %d  |  %d linhas  |  margem %s", "receiving  |  %d LPM, IOC %d  |  %d lines  |  margin %s"},
    {"pela fase", "by phasing"},
    {"%s  |  sinal %.0f dB  |  %d imagens recebidas", "%s  |  signal %.0f dB  |  %d images received"},
    {"analise pronta - clique Reiniciar para medir de novo", "analysis done - click Restart to measure again"},
    {"juntando audio: %.0f de %.0f s", "collecting audio: %.0f of %.0f s"},
    {"nao achei ", "not found: "},
    {"CreatePipe falhou", "CreatePipe failed"},
    {"nao consegui criar o cano ", "could not create the pipe "},
    {"nao consegui abrir ", "could not start "},
    {" (erro ", " (error "},
    {"faltou a banda ou a taxa", "missing band or sample rate"},
    {"[HFDL] dumphfdl iniciado - %d canais, centro %.3f MHz, %.3f Msps\n", "[HFDL] dumphfdl started - %d channels, centre %.3f MHz, %.3f Msps\n"},
    {"[AIS] AIS-catcher iniciado - canais 161,975 e 162,025 MHz. Mapa: http://127.0.0.1:%d\n", "[AIS] AIS-catcher started - channels 161.975 and 162.025 MHz. Map: http://127.0.0.1:%d\n"},
    {"  %.1f nós", "  %.1f kn"},
    {"  rumo %.0f°", "  course %.0f°"},
    {"%d navios", "%d ships"},
    {"nao consegui gravar ", "could not write "},
    {"[APRS] direwolf iniciado - HF, 300 baud (USB)\n", "[APRS] direwolf started - HF, 300 baud (USB)\n"},
    {"[APRS] direwolf iniciado - VHF, 1200 baud (FM)\n", "[APRS] direwolf started - VHF, 1200 baud (FM)\n"},
    {"[APRS] a porta AGW do direwolf nao respondeu - os pacotes vem pelo texto (com atraso)\n", "[APRS] direwolf's AGW port did not answer - packets come through the text output (delayed)\n"},
    {"AGW em tempo real", "AGW in real time"},
    {"esperando o primeiro pacote", "waiting for the first packet"},
    {"faltou o canal ou a taxa", "missing channel or sample rate"},
    {"[ACARS] acarsdec iniciado - canais", "[ACARS] acarsdec started - channels"},
    {" MHz, ao mesmo tempo\n", " MHz, at the same time\n"},
    {"faltou o canal", "missing channel"},
    {"o VDL2 precisa do dongle em 1,05 Msps", "VDL2 needs the dongle at 1.05 Msps"},
    {"[VDL2] dumpvdl2 iniciado - canais", "[VDL2] dumpvdl2 started - channels"},
    {" UTC  dream iniciado - procurando o sinal DRM...\n", " UTC  dream started - searching for the DRM signal...\n"},
    {"estéreo", "stereo"},
    {"estéreo paramétrico", "parametric stereo"},
    {"  (modo %c, %.0f kHz, %s %.1f kbps, SNR %.1f dB)", "  (mode %c, %.0f kHz, %s %.1f kbps, SNR %.1f dB)"},
    {" UTC  Estacao: ", " UTC  Station: "},
    {"sem cripto", "no encryption"},
    {"Faltam arquivos do TETRA na pasta decoders (tetra-rx.exe, cdecoder.exe, sdecoder.exe).", "TETRA files are missing from the decoders folder (tetra-rx.exe, cdecoder.exe, sdecoder.exe)."},
    {"nao consegui reservar a porta UDP do TETMON", "could not reserve the TETMON UDP port"},
    {"nao consegui abrir o tetra-rx.exe (erro ", "could not start tetra-rx.exe (error "},
    {"[TETRA] iniciado - pi/4-DQPSK 18 ksimb/s, osmo-tetra + ACELP", "[TETRA] started - pi/4-DQPSK 18 ksym/s, osmo-tetra + ACELP"},
    {" (espectro invertido)", " (inverted spectrum)"},
    {"\n[TETRA] procurando a portadora (1 s de aquisicao)...\n", "\n[TETRA] searching for the carrier (1 s acquisition)...\n"},
    {"[TETRA] portadora a %+.0f Hz do VFO - acompanhando\n", "[TETRA] carrier at %+.0f Hz from the VFO - tracking\n"},
    {"livre", "free"},
    {"ocupado", "busy"},
    {"o tetra-rx fechou sozinho", "tetra-rx closed by itself"},
    {"Celula: MCC %ld  MNC %ld  CC %ld", "Cell: MCC %ld  MNC %ld  CC %ld"},
    {"Frequencias da celula: descida %.4f MHz, subida %.4f MHz", "Cell frequencies: downlink %.4f MHz, uplink %.4f MHz"},
    {"Frequencia da celula (descida): %.4f MHz", "Cell frequency (downlink): %.4f MHz"},
    {"Criptografia da celula: ", "Cell encryption: "},
    {"Chamada: SSI ", "Call: SSI "},
    {"Chamada conectada: SSI ", "Call connected: SSI "},
    {"Fala liberada para SSI ", "Talk granted to SSI "},
    {"Chamada encerrada", "Call ended"},
    {"Status de SSI ", "Status from SSI "},
    {"SDS (mensagem curta) de SSI ", "SDS (short message) from SSI "},
    {"P25 fase 1", "P25 phase 1"},
    {"P25 fase 2", "P25 phase 2"},
    {"O decodificador DMR (dsd-fme) precisa do Windows 8.1, 10 ou 11 - no Windows 7 ele nao abre.", "The DMR decoder (dsd-fme) needs Windows 8.1, 10 or 11 - it does not run on Windows 7."},
    {"Nao achei decoders\\dsd-fme.exe ao lado do RXSDR.exe.", "decoders\\dsd-fme.exe not found next to RXSDR.exe."},
    {"sem socket UDP", "no UDP socket"},
    {"nao consegui reservar a porta UDP da voz", "could not reserve the voice UDP port"},
    {"nao consegui abrir o dsd-fme.exe (erro ", "could not start dsd-fme.exe (error "},
    {"[DMR] dsd-fme iniciado - modo ", "[DMR] dsd-fme started - mode "},
    {" (invertido)", " (inverted)"},
    {"o dsd-fme fechou", "dsd-fme closed"},
    {"o dsd-fme fechou sozinho", "dsd-fme closed by itself"},
    {"Grupo", "Group"},
    {"Privado", "Private"},
    {"Dados", "Data"},
    {"Tipo de aparelho desconhecido: ", "Unknown device type: "},
    {"Nao foi possivel abrir o ", "Could not open "},
    {"waveOutOpen falhou (", "waveOutOpen failed ("},
};

const Par kListas[] = {
    {"Outros horários nesta frequência", "Other times on this frequency"},
    {"Sem horário conhecido", "No known schedule"},
    {"sem horário", "no schedule"},
    {"PACTOR-I - antes estava na lista do SITOR-B", "PACTOR-I - previously in the SITOR-B list"},
    {"A lista publica ", "The list says "},
    {", mas o sinal sai em ", ", but the signal is at "},
    {"(medido no RXSDR: tons em ", "(measured in RXSDR: tones at "},
    {"Na lista constava ", "The list had "},
    {"; o sinal sai em ", "; the signal is at "},
    {"(medido no RXSDR em ", "(measured in RXSDR on "},
    {" tons em ", " tones at "},
    {"Avisos-Rádio Náuticos e SAR", "Navigational warnings and SAR"},
    {"Estação Rádio da Marinha no Rio de Janeiro (NAVAREA V), em USB:", "Brazilian Navy radio station in Rio de Janeiro (NAVAREA V), USB:"},
    {"meteoromarinha / avisos", "marine weather / warnings"},
    {"Meteoromarinha", "Marine weather"},
    {"Marinha do Brasil", "Brazilian Navy"},
    {"Marinha argentina / costeiras", "Argentine Navy / coastal"},
    {"Marinha argentina", "Argentine Navy"},
    {" - Marinha - ", " - Navy - "},
    {"Sai só a pedido do navegante", "Only on request from ships"},
    {"só a pedido", "on request only"},
    {") - principal", ") - main"},
    {"Forças Armadas", "Armed Forces"},
    {"Brasília e outras", "Brasília and others"},
    {" ou outra", " or other"},
    {"navio / móvel", "ship / mobile"},
    {"DSC costeiro", "coastal DSC"},
    {"(a mais movimentada)", "(the busiest)"},
    {"a mais movimentada", "the busiest"},
    {"(o mais ativo)", "(the most active)"},
    {"... e mais ", "... plus "},
    {"estações", "stations"},
    {"Outros - Central de Urgências", "Others - Emergency centre"},
    {"Radioamador", "Amateur radio"},
    {"radioamador", "amateur radio"},
    {"(meteorologia)", "(weather)"},
    {"(ondas longas)", "(long wave)"},
    {"Ministério do Exterior - Cartum (Sudão)", "Foreign Ministry - Khartoum (Sudan)"},
    {"Faixa do Cidadão (PX), canal", "Citizens Band (CB), channel"},
    {"repetidoras em FM", "FM repeaters"},
    {"eventos ARISS", "ARISS events"},
    {"APRS de HF", "HF APRS"},
    {"frequência do mostrador", "dial frequency"},
    {"OM - Ondas Médias (radiodifusão)", "MW - Medium Wave (broadcast)"},
    {"Ondas médias e curtas (HF)", "Medium and short wave (HF)"},
    {"FM - radiodifusão", "FM - broadcast"},
    {"Aviação", "Aviation"},
    {"Marítimo - canal", "Maritime - channel"},
    {"Rádios comunicadores", "Walkie-talkies"},
    {"Satélite militar", "Military satellite"},
    {"Voz da China", "Voice of China"},
    {"Coreia do Norte", "North Korea"},
    {"Nova Zelândia (Pacífico)", "New Zealand (Pacific)"},
    {"(para a Índia)", "(to India)"},
    {"Leste Europeu", "Eastern Europe"},
    {"África Ocidental", "West Africa"},
    {"África Oriental", "East Africa"},
    {"América do Sul", "South America"},
    {"Américas", "Americas"},
    {"Europa", "Europe"},
    {"Alemanha", "Germany"},
    {"França", "France"},
    {"Romênia", "Romania"},
    {"Inglaterra", "England"},
    {"Índia", "India"},
    {"Japão", "Japan"},
    {"Pequim", "Beijing"},
    {"Brasil", "Brazil"},
    {"EUA", "USA"},
    {"francês", "French"},
    {"inglês", "English"},
    {"chinês", "Chinese"},
    {"coreano", "Korean"},
    {"alemão", "German"},
    {"italiano", "Italian"},
    {"espanhol", "Spanish"},
    {"música", "music"},
    {"Marinha", "Navy"},
};

const Par kAvisos[] = {
    {"[tom central medido: ", "[measured centre tone: "},
    {"[nao consegui medir o tom - usando o valor da tela]", "[could not measure the tone - using the on-screen value]"},
    {"[tom medido: ", "[measured tone: "},
    {"[tom mudou: ", "[tone changed: "},
};

const Par kDsc[] = {
    {"formato desconhecido (", "format unknown ("},
    {"formato ", "format "},
    {" | para ", " | to "},
    {" | de ", " | from "},
    {" | pede confirmacao", " | ack requested"},
    {" | confirmacao", " | acknowledgement"},
    {" | fim", " | end"},
    {" | ECC FALHOU", " | ECC FAILED"},
    {"estacao individual", "individual station"},
    {"chamada seletiva", "selective call"},
    {"todos os navios", "all ships"},
    {"area geografica", "geographic area"},
    {"socorro", "distress"},
    {"urgencia", "urgency"},
    {"seguranca", "safety"},
    {"rotina", "routine"},
    {"grupo", "group"},
};

const Par kAnalise[] = {
    {"Audio insuficiente. Deixe a janela aberta com o sinal presente.", "Not enough audio. Keep the window open with the signal present."},
    {"Falha ao calcular o espectro.", "Failed to compute the spectrum."},
    {"Portadora unica em ", "Single carrier at "},
    {" Hz - nao e FSK.", " Hz - not FSK."},
    {"Sem energia suficiente para medir.", "Not enough energy to measure."},
    {"Envoltoria: media ", "Envelope: mean "},
    {" do pico | ligado em ", " of peak | on during "},
    {"Portadora limpa, sem liga-desliga. Pode ser CW em repouso,", "Clean carrier, no on-off keying. May be idle CW,"},
    {"piloto, ou sinal de fase (PSK) - que este analisador nao le.", "a pilot, or a phase signal (PSK) - which this analyzer cannot read."},
    {"PULSADA: fica apagada a maior parte do tempo, em rajadas curtas.", "PULSED: off most of the time, in short bursts."},
    {"Rajadas repetindo a cada ", "Bursts repeating every "},
    {" por segundo).", " per second)."},
    {"Tipico de leitor RFID, telemetria ou baliza que chama em ciclo.", "Typical of RFID readers, telemetry or beacons calling in a cycle."},
    {"Modulada em AMPLITUDE - a informacao esta no acender e apagar.", "AMPLITUDE modulated - the information is in the on/off."},
    {"Ritmo principal: ", "Main rate: "},
    {"Nao ha texto a extrair por aqui: a leitura de amplitude", "There is no text to extract here: the amplitude reading"},
    {"so mostra o ritmo, nao o conteudo.", "only shows the rate, not the content."},
    {"Nao achei dois tons claros.", "Could not find two clear tones."},
    {"Nenhum pico se destaca do ruido - o sinal pode estar fraco ou ser de fase (PSK).", "No peak stands out from the noise - the signal may be weak or phase-modulated (PSK)."},
    {"Um unico tom em ", "A single tone at "},
    {" Hz - portadora continua, CW ou sinal de fase.", " Hz - continuous carrier, CW or phase signal."},
    {"Os dois picos estao a so ", "The two peaks are only "},
    {" Hz - estreito demais para FSK.", " Hz apart - too narrow for FSK."},
    {"Os dois tons nao se revezam (", "The two tones do not alternate ("},
    {"% num estado, ", "% in one state, "},
    {"% no outro).", "% in the other)."},
    {"Os dois tons se revezam: ", "The two tones alternate: "},
    {"% do tempo - e FSK.", "% of the time - it is FSK."},
    {"% do tempo", "% of the time"},
    {"(a correlacao crua deu ", "(the raw correlation was "},
    {" por causa do desvanecimento, que sobe e desce os dois tons juntos)", " because of fading, which raises and lowers both tones together)"},
    {"Tons: ", "Tones: "},
    {"Deslocamento (shift): ", "Shift: "},
    {"Atencao: achei ", "Warning: found "},
    {" picos - pode ser multitom (MFSK) ou haver outro sinal junto.", " peaks - may be multitone (MFSK) or another signal alongside."},
    {"Velocidade: ", "Speed: "},
    {" baud (raia ", " baud (clock line "},
    {"x acima do fundo)", "x above the floor)"},
    {"RTTY amador (45,45)", "Amateur RTTY (45.45)"},
    {"Compativel com:", "Compatible with:"},
    {"Nao consegui medir a velocidade com seguranca.", "Could not measure the speed reliably."},
    {"Sem raia de relogio clara: sinal fraco, intermitente, ou nao e FSK simples.", "No clear clock line: weak or intermittent signal, or not simple FSK."},
    {" - identico ao SITOR-B na forma", " - same shape as SITOR-B"},
    {"RTTY comercial ou de imprensa", "Commercial or press RTTY"},
    {"RTTY comercial", "Commercial RTTY"},
    {"A velocidade nao foi medida, entao a lista esta larga.", "The speed was not measured, so the list is broad."},
    {"Estes modos tem a MESMA forma no ar. Quem separa e a frequencia:", "These modes have the SAME shape on the air. The frequency tells them apart:"},
    {"O deslocamento de ", "The shift of "},
    {" Hz e o da familia SITOR-B / DSC / RTTY,", " Hz belongs to the SITOR-B / DSC / RTTY family,"},
    {"mas a velocidade que medi (", "but the speed I measured ("},
    {" baud) nao bate com nenhum deles.", " baud) matches none of them."},
    {"Desconfie da velocidade, nao do sinal: tente 100 baud (SITOR-B, DSC)", "Doubt the speed, not the signal: try 100 baud (SITOR-B, DSC)"},
    {" direto no decodificador.", " directly in the decoder."},
    {"Deslocamento de ", "Shift of "},
    {" Hz nao bate com os modos que conheco.", " Hz does not match the modes I know."},
    {"Pode ser servico militar, telemetria ou modo proprietario.", "May be a military service, telemetry or a proprietary mode."},
    {"Bits analisados: ", "Bits analyzed: "},
    {" | proporcao de uns: ", " | ratio of ones: "},
    {" | media das sequencias: ", " | mean run length: "},
    {"Conteudo: indistinguivel de bits aleatorios.", "Content: indistinguishable from random bits."},
    {"ATENCAO: isso tem DUAS explicacoes possiveis, e este teste", "WARNING: this has TWO possible explanations, and this test"},
    {"nao separa as duas:", "cannot tell them apart:"},
    {"1) a transmissao e mesmo cifrada;", "1) the transmission really is encrypted;"},
    {"2) a velocidade medida acima esta errada, e os bits", "2) the speed measured above is wrong, and the bits"},
    {"estao sendo lidos fora de compasso.", "are being read out of step."},
    {"Antes de concluir, confira a velocidade contra o que se espera", "Before concluding, check the speed against what is expected"},
    {"do modo (SITOR-B e DSC sao 100 baud; RTTY 45,45, 50 ou 75).", "for the mode (SITOR-B and DSC are 100 baud; RTTY 45.45, 50 or 75)."},
    {"Conteudo: sem estrutura clara. Pode ser cifrado, ou o sinal esta fraco demais.", "Content: no clear structure. May be encrypted, or the signal is too weak."},
    {"Conteudo: tem estrutura, nao e aleatorio.", "Content: structured, not random."},
    {"Vale tentar um decodificador de texto com esses parametros.", "Worth trying a text decoder with these parameters."},
    {" e 518 kHz", " and 518 kHz"},
    {" Hz e ", " Hz and "},
    {"% e ", "% and "},
    {"ou 45,45", "or 45.45"},
    {" (100 baud, 170 Hz)", " (100 baud, 170 Hz)"},
    {"45,45", "45.45"},
    {"4209,5", "4209.5"},
    {"16806,5", "16806.5"},
    {"2187,5", "2187.5"},
    {"4207,5", "4207.5"},
    {"8414,5", "8414.5"},
    {" ou ", " or "},
};

const std::unordered_map<std::string_view, const char*>& mapa()
{
    static const std::unordered_map<std::string_view, const char*> m = [] {
        std::unordered_map<std::string_view, const char*> r;
        r.reserve(sizeof kTextos / sizeof kTextos[0] * 2);
        for (const Par& p : kTextos) r.emplace(p.pt, p.en);
        return r;
    }();
    return m;
}

template <size_t N>
void trocar(std::string& s, const Par (&tab)[N])
{
    for (const Par& p : tab) {
        const size_t lp = std::strlen(p.pt), le = std::strlen(p.en);
        for (size_t k = s.find(p.pt); k != std::string::npos; k = s.find(p.pt, k + le))
            s.replace(k, lp, p.en);
    }
}

bool digito(char c) { return c >= '0' && c <= '9'; }

// "(118 a 137)" -> "(118 to 137)"; "1200 e 1400" -> "1200 and 1400"
void entreNumeros(std::string& s)
{
    for (size_t k = 1; k + 3 < s.size(); ++k) {
        if (!digito(s[k - 1]) || s[k] != ' ' || s[k + 2] != ' ' || !digito(s[k + 3])) continue;
        if (s[k + 1] == 'a') { s.replace(k, 3, " to "); k += 3; }
        else if (s[k + 1] == 'e') { s.replace(k, 3, " and "); k += 4; }
    }
}

} // namespace

void definirIngles(bool en) { g_ingles = en; }
bool emIngles() { return g_ingles; }

const char* T(const char* pt)
{
    if (!g_ingles || !pt) return pt;
    const auto& m = mapa();
    const auto it = m.find(std::string_view(pt));
    return it == m.end() ? pt : it->second;
}

std::string T(const std::string& pt)
{
    if (!g_ingles) return pt;
    const auto& m = mapa();
    const auto it = m.find(std::string_view(pt));
    return it == m.end() ? pt : std::string(it->second);
}

std::string TLs(const std::string& pt)
{
    if (!g_ingles || pt.empty()) return pt;
    std::string s = pt;
    trocar(s, kListas);
    entreNumeros(s);
    return s;
}

const char* TL(const char* pt)
{
    if (!g_ingles || !pt || !*pt) return pt;
    static std::mutex mx;
    static std::unordered_map<const char*, std::string> guardados;   // os nos nao mudam de lugar
    std::lock_guard<std::mutex> lk(mx);
    auto it = guardados.find(pt);
    if (it == guardados.end()) it = guardados.emplace(pt, TLs(pt)).first;
    return it->second.c_str();
}

std::string TAvisos(const std::string& s)
{
    if (!g_ingles || s.find('[') == std::string::npos) return s;
    std::string r = s;
    trocar(r, kAvisos);
    return r;
}

std::string TDsc(const std::string& s)
{
    if (!g_ingles || s.empty()) return s;
    std::string r = TAvisos(s);
    trocar(r, kDsc);
    return r;
}

std::string TAnalise(const std::string& s)
{
    if (!g_ingles || s.empty()) return s;
    std::string r = s;
    trocar(r, kAnalise);
    return r;
}

} // namespace masdr
